package com.trading.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Represents a trading decision generated by the strategy service.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TradingDecision {
    
    public enum Action {
        BUY, SELL, HOLD
    }
    
    private String symbol;
    private Action action;
    private double amount;           // Amount in USDT or base currency
    private double confidence;       // Confidence score (0-1)
    private String reason;           // Explanation for the decision
    private Instant timestamp;
    
}
